apiVersion: v1
kind: Pod
metadata: 
  name: app-secret-env-3
spec:
  containers:
    - name: mycontainer
      image: redis
      env:
        - name: SECRET_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mysecret1
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret1
              key: password
  restartPolicy: Always
